name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created
    

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Build
      run: |
        make build

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: klippup
        path: klippup
        retention-days: 5
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: klippup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


