name: Go Build

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Build
      run: |
        make build

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: klippup
        path: klippup
        retention-days: 5


